// var PouchSync = require('pouch-websocket-sync');
// var Websocket = require('websocket-stream');
// var psms = require('pouch-stream-multi-sync');
var Transform = require('readable-stream/transform');
// var inherits = require('inherits')
// var WebSocketServer = require('ws').Server
// var through = require('through2')
// var duplexify = require('duplexify')
// var WS = require('ws')
var TransformStream = require('stream').Transform;
root.innerText = `should be function: ${typeof TransformStream}`
// var prs = require('pouch-remote-stream');
